### ISSUE TITLE
Nothing to select

### ISSUE THREAD

**Issue by cbfsocial** [radiance-project/ear-pc#12]
Hi.
I have an issue with connecting my Ear 1 with app.
I tryed to made a new connection by the app but got an error from https://github.com/radiance-project/ear-pc/issues/7
Now i connected pods to PC via bluetooth and using it but app cant find them.
could you please assist with issue?

thanks in advance

**Comment by cbfsocial** [comment]
https://github.com/radiance-project/ear-pc/assets/19409332/6c8453eb-da8a-41eb-8588-b6a65b73788b

**Comment by Lisra-git** [comment]
Hey are you on discord by any chance? Please contact me @RapidZapper

**Comment by cbfsocial** [comment]
Sure. Send you an invite

**Comment by cbfsocial** [comment]
Updated ear firmware to latest.
Reinstalled the app
Run as admin.

Fixed

**Comment by Xcution3r** [comment]
> Updated ear firmware to latest. Reinstalled the app Run as admin.
> 
> Fixed

bro still can't find them, can you help me

**Comment by Lisra-git** [comment]
> > Updated ear firmware to latest. Reinstalled the app Run as admin.
> > Fixed
> 
> bro still can't find them, can you help me

Hey
Please check that
https://earweb.bttl.xyz/
