### ISSUE TITLE
Error after selecting device

### ISSUE THREAD

**Issue by sebascorreia** [radiance-project/ear-pc#13]
![ear](https://github.com/radiance-project/ear-pc/assets/65636374/0d25036d-a56c-4125-bc43-0c3128cf9771)

I got the newest launcher.exe, used it to download and install the rest. pressed ear-pc.exe. At first it worked but then i realized the right earphone wasnt on so i had to redo the connection. When i tried again the error you can see above happened. Its like its only an image i cant really control anything. I tried deleting and reinstalling, i tried removing the bluetooth device and trying again, i tried restarting my pc, running as admin. etc. nothing worked. ngl your app is kinda bugging my old ass laptop, dont mean to be rude, i know you guys probably are working hard on it, but do you know if theres any way i can change the controls without using the app? All i want is to activate the noise cancellation while i use it on my laptop.

**Comment by mrbrickstar** [comment]
Hi sebascorreia, 
thank you for pointing out this issues to us, this should definitely not happen and we are happy to assist you with this. 
For now, please press ctrl + shift + i and tell us if you see any errors. Some information on what computer you are using would be helpful.

Also, this project is open source and you are welcome to contribute to help us fix all the bugs. If you can't, please at least open an issue on GitHub to let us know about any further bugs you might find.

I'm looking forward to hear from you :)
Bendix
