### ISSUE TITLE
CMF Buds Pro

### ISSUE THREAD

**Issue by Alex16992** [radiance-project/ear-pc#17]
Can you please add their support? The app doesn't find anything when I connect them...

**Comment by mrbrickstar** [comment]
Hey Alex,
support for CMF Buds is planned, but we don't have an eta on when it will arrive in the app.

**Comment by mentex23** [comment]
would really like to see that too..

**Comment by alaukikpachauri** [comment]
please provide the support for cmf buds pro too as soon as possible

**Comment by noobxterr** [comment]
yep came for cmf buds pro, and now idk how to uninstall the app even

**Comment by BrandgrandRealMe** [comment]
Also came for CMF buds pro.

**Comment by txrmsconditions** [comment]
support for the normal (non-pro) CMF Buds would also be cool :))

**Comment by Anas15102** [comment]
cmf neckband too

**Comment by Lisra-git** [comment]
CMF Buds Pro is now supported on Ear (web)
https://github.com/radiance-project/ear-pc/releases/tag/Web
