### ISSUE TITLE
cannot Uninstall ear pc

### ISSUE THREAD

**Issue by Vikkkky** [radiance-project/ear-pc#18]
I cannot uninstall ear pc. Cause I cannot open Files explorer, it pops up a blank screen and thats it. How do i fix this?

**Comment by noobxterr** [comment]
same problem, neither does it show on the apps list

**Comment by mrbrickstar** [comment]
Heya, to uninstall, simply navigate to C:\Users\YourUsername\AppData\Local\Programs and delete the ear-pc folder.
