### ISSUE TITLE
May I ask which software design software to use? I want to learn software design.

### ISSUE THREAD

**Issue by Cwy0116** [radiance-project/ear-pc#20]
I want to make a software, just want to study art design.

**Comment by mrbrickstar** [comment]
We used a mix of figma and Adobe XD to do the first mockups and then used simple html + tailwind to build the frontend.

**Comment by Knockoi** [comment]
I'm new to software, how do I create my first software?
(I want to be able to use it on Window, IOS, Android)

**Comment by Cwy0116** [comment]
> We used a mix of figma and Adobe XD to do the first mockups and then used simple html + tailwind to build the frontend.

How does FIGMA work with ESP32?
I have already made a FIGMA project, how to connect the Bluetooth together?

**Comment by mrbrickstar** [comment]
Figma is purely used to design software and so mockups, there are some Plugins that can convert figma projects into code but most of them are very buggy and unreliable. 

But as this is not related to Ear (PC) I'd ask you to continue this conversation elsewhere
