### ISSUE TITLE
New Nothing Ear Support 

### ISSUE THREAD

**Issue by jcf-junior** [radiance-project/ear-pc#22]
Hello, I'd like to request support for the new Nothing Ear (2024)

**Comment by Lisra-git** [comment]
Should be coming with next update

**Comment by vitalysacred** [comment]
> Should be coming with next update
awesome! can't wait it

**Comment by try2hack** [comment]
waiting for Nothing ear (a) supported.

**Comment by boooonu** [comment]
Any ETA For Next Update? (Nothing Ear)

**Comment by Lisra-git** [comment]
Nothing Ear is now supported with Ear (web)
https://github.com/radiance-project/ear-pc/releases/tag/Web
