### ISSUE TITLE
Linux support 

### ISSUE THREAD

**Issue by shadowe1ite** [radiance-project/ear-pc#23]

**Comment by yoyonel** [comment]
Hi,
I'm on Linux/Debian 11, i'm very interrested to have Linux Support for my BUDS PRO 2.
How i can help you for this support ? (i'm (Linux) Python backend dev, i can dev in C/C++ too).

**Comment by shadowe1ite** [comment]
> Hi, I'm on Linux/Debian 11, i'm very interrested to have Linux Support for my BUDS PRO 2. How i can help you for this support ? (i'm (Linux) Python backend dev, i can dev in C/C++ too).

Hey I made a simple script  in c and python for cmf buds that perform basic operations such as enable disable anc, low latency, bass etc, (cli).
You can check it out if your interested

**Comment by yoyonel** [comment]
> > Hi, I'm on Linux/Debian 11, i'm very interrested to have Linux Support for my BUDS PRO 2. How i can help you for this support ? (i'm (Linux) Python backend dev, i can dev in C/C++ too).
> 
> Hey I made a simple script in c and python for cmf buds that perform basic operations such as enable disable anc, low latency, bass etc, (cli). You can check it out if your interested

Hi, Where can i found theses scripts please ? (they work on linux environment ?)

**Comment by shadowe1ite** [comment]
> > > Hi, I'm on Linux/Debian 11, i'm very interrested to have Linux Support for my BUDS PRO 2. How i can help you for this support ? (i'm (Linux) Python backend dev, i can dev in C/C++ too).
> > 
> > 
> > Hey I made a simple script in c and python for cmf buds that perform basic operations such as enable disable anc, low latency, bass etc, (cli). You can check it out if your interested
> 
> Hi, Where can i found theses scripts please ? (they work on linux environment ?)

https://github.com/shadowelite-sec/ear

I think it's only works with cmf buds 1 

https://bharadwaj-raju.github.io/posts/nothing-ear-2-on-linux/

You may need to follow these steps to create one for your device

**Comment by Lisra-git** [comment]
Hey
Ear (web) is now available which should have Linux support, work on CMF Buds and Buds Pro 2 :)
https://github.com/radiance-project/ear-pc/releases/tag/Web
