### ISSUE TITLE
Nothing ear(a)

### ISSUE THREAD

**Issue by xorCoding** [radiance-project/ear-pc#24]
Hi, are the Nothing Ear(a) supported? Because when I scan the devices I can't find them.

**Comment by Fan4eGGG** [comment]
agreed. cant find my Ear (a) too. pls add support

**Comment by DelovoyDrew** [comment]
Hi there, I also need support for Nothing Ear(a)

**Comment by Fan4eGGG** [comment]
> Hi there, I also need support for Nothing Ear(a)

[this](https://github.com/radiance-project/ear-pc/issues/27#issuecomment-2142837423)

**Comment by Lisra-git** [comment]
Probably delayed to july

**Comment by Fan4eGGG** [comment]
> Probably delayed to july

how's it going?

**Comment by psych0kines** [comment]
probably delayed to december (:

**Comment by Kucchan67346** [comment]
I'd love to see it released as a beta version, even if it's just a work in progress.

**Comment by P40L0X** [comment]
Waiting for my ear (a) being supported...

**Comment by reuvenal0** [comment]
When will we get support for ear (a)?

**Comment by mr-d3falt** [comment]
Same can't add ear a to Windows 10 PC :(

**Comment by Lisra-git** [comment]
Ear (web) is now available with Ear (a) support coming next week
https://github.com/radiance-project/ear-pc/releases/tag/Web
