### ISSUE TITLE
Request to add the backend to the public. 

### ISSUE THREAD

**Issue by praveenvino39** [radiance-project/ear-pc#25]
I believe when you mention `backend`, you mean the core Python file responsible for sending commands to the Bluetooth device when paired. I agree that altering this file could lead to bricking the device. However, as users of the Ear-PC, we currently don't know what is written in that Python file. Making this file private gives the project owner full control, which could lead to potential issues. Therefore, I'm requesting you to make that core Python file public and carefully monitor/review all pull requests to avoid any suspicious code being merged.

**Comment by Lisra-git** [comment]
Will be disclosed with next update
