### ISSUE TITLE
Icon Is Miscoloured

### ISSUE THREAD

**Issue by boooonu** [radiance-project/ear-pc#28]
Assuming The Icon Is Meant To Depict The Main Series (Ear (1), Ear (2), Ear) In The White Colour
One Of The **Earbuds (Left) Should Have A White Dot, Instead Of A Red Dot.** 
This Is The Way The Ear Is Coloured IRL. Below Is A Reference (Made In Paint):
![image](https://github.com/radiance-project/ear-pc/assets/109607240/8569507b-f298-4947-bf40-2871a5f166fb)

**Comment by Lisra-git** [comment]
The other is just the right stick haha, nothing wrong here but I get your point
