### ISSUE TITLE
ARM architecture

### ISSUE THREAD

**Issue by Teo230** [radiance-project/ear-pc#29]
Hi, does the software support ARM architecture? I currently have Windows on ARM M1 MacBook but seems not working

**Comment by P40L0X** [comment]
I also add I'm using Windows 11 on ARM (24H2) on new Copilot+ PCs (e.g. Lenovo Yoga Slim 7x) and the app doesn't work.
An ARM64 variant would be great.

**Comment by Lisra-git** [comment]
That's definitely something I wasn't able to test, but that shouldn't be a problem with future release

**Comment by P40L0X** [comment]
> That's definitely something I wasn't able to test, but that shouldn't be a problem with future release

Any ETA for the new release?
Will it also support Nothing Ear (a)?

**Comment by Lisra-git** [comment]
> > That's definitely something I wasn't able to test, but that shouldn't be a problem with future release
> 
> Any ETA for the new release? Will it also support Nothing Ear (a)?

Ear (web) is now available which should solve the problem with ARM
Ear (a) support is coming next week
https://github.com/radiance-project/ear-pc/releases/tag/Web
