### ISSUE TITLE
Hello! What about a new update?

### ISSUE THREAD

**Issue by psych0kines** [radiance-project/ear-pc#31]
it's just been 6* months since the release of the latest tws. would like to see a new version, otherwise I can't enable the "reduce latency" feature without it. or do you have to donate somewhere to subscribe to Patreon?
thanks!

**Comment by Fan4eGGG** [comment]
i think its dead

**Comment by Lisra-git** [comment]
Check this thread for updates about the project, https://nothing.community/d/7185-ear-pc-unofficial-nothing-x-app-for-pc/63
Should be coming soon, just making sure everything is perfect

**Comment by psych0kines** [comment]
> just making sure everything is perfect

ie it could take another year.
wish you had a Patreon where we could help you speed up development!

**Comment by Fan4eGGG** [comment]
[this](https://github.com/radiance-project/ear-pc/issues/32#issuecomment-2332697271)

**Comment by Lisra-git** [comment]
Ear (web) is now available with Ear (a) support coming next week
https://github.com/radiance-project/ear-pc/releases/tag/Web

**Comment by Fan4eGGG** [comment]
> Ear (web) is now available with Ear (a) support coming next week https://github.com/radiance-project/ear-pc/releases/tag/Web

I dont use the browser on pc, how can i use your app then?
why is the pc app canceled?

**Comment by Lisra-git** [comment]
> > Ear (web) is now available with Ear (a) support coming next week https://github.com/radiance-project/ear-pc/releases/tag/Web
> 
> I dont use the browser on pc, how can i use your app then? why is the pc app canceled?

I doubt you are using a PC without a browser, that said everything is explained in this update https://nothing.community/d/7185-ear-pc-unofficial-nothing-x-app-for-pc/63
Overall just much easier to maintain across all platforms

**Comment by Fan4eGGG** [comment]
> I doubt you are using a PC without a browser

I have a ultra-specific situation on this, briefly, when I work on my PC I need to close browsers. for music I use Spotify.

> Overall just much easier to maintain across all platforms

it's a pity that the headphones themselves (_in my case ear (a)_) don't have a function to enable **low latency** (_for which I was waiting for this app to be released_) like my second headphones **enco free 3**.
how much easier it would be to just press a button and have everything work, ehhh.

**Comment by Lisra-git** [comment]
> > I doubt you are using a PC without a browser
> 
> I have a ultra-specific situation on this, briefly, when I work on my PC I need to close browsers. for music I use Spotify.
> 
> > Overall just much easier to maintain across all platforms
> 
> it's a pity that the headphones themselves (_in my case ear (a)_) don't have a function to enable **low latency** (_for which I was waiting for this app to be released_) like my second headphones **enco free 3**. how much easier it would be to just press a button and have everything work, ehhh.

You can enable it from your phone using dual connection

**Comment by Fan4eGGG** [comment]
> You can enable it from your phone using dual connection

Of course I know about it, but it just doesn't work no matter how hard I try.
and I read on reddit that it only works with the Nothing for PC app.

**Comment by bastianfbr** [comment]
> > I doubt you are using a PC without a browser
> 
> I have a ultra-specific situation on this, briefly, when I work on my PC I need to close browsers. for music I use Spotify.
> 
> > Overall just much easier to maintain across all platforms
> 
> it's a pity that the headphones themselves (_in my case ear (a)_) don't have a function to enable **low latency** (_for which I was waiting for this app to be released_) like my second headphones **enco free 3**. how much easier it would be to just press a button and have everything work, ehhh.

Just install the PWA...

**Comment by Fan4eGGG** [comment]
> PWA

add some information tho

**Comment by bastianfbr** [comment]
> > PWA
> 
> add some information tho

Open your browser
Visit https://earweb.bttl.xyz/
Search for the install ear (web) application like : 
![image](https://github.com/user-attachments/assets/71bbca84-3c9b-425f-bd60-5a926443b527)

![image](https://github.com/user-attachments/assets/15f1aed4-7090-4bf7-9405-b1d762aa3811)


Then you just have to open ear (web) and not the browser.

**Comment by Fan4eGGG** [comment]
> Search for the install ear (web) application like

cant find it. Am I looking in the wrong place?

**Comment by bastianfbr** [comment]
> > Search for the install ear (web) application like
> 
> cant find it. Am I looking in the wrong place?
You can also check it in the context menu on the right > Applications
![image](https://github.com/user-attachments/assets/c125454d-0f6a-4518-a2b8-86a72d488990)

**Comment by Fan4eGGG** [comment]
> > You can also check it in the context menu on the right > Applications
> > ![image](https://private-user-images.githubusercontent.com/29505634/372397194-c125454d-0f6a-4518-a2b8-86a72d488990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODE2MzIsIm5iZiI6MTcyNzc4MTMzMiwicGF0aCI6Ii8yOTUwNTYzNC8zNzIzOTcxOTQtYzEyNTQ1NGQtMGY2YS00NTE4LWEyYjgtODZhNzJkNDg4OTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDExMTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODg2NWNmYWExM2JmNDFiMDQwMDVmNjg1NTMxNGYzNzI3ODBmMWU5OTY5ZjlkYjY3M2U0MWRkYTgxOTU5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j1t_4UXfGh_E4lgaox-zwVS0CaBJwQ6GVvLTGOFnH6k)

nah. so i'm not wrong. i don't have any Applications. i use Opera, maybe that's why.

**Comment by tunaflsh** [comment]
> nah. so i'm not wrong. i don't have any Applications. i use Opera, maybe that's why.

Opera doesn't support PWA.

**Comment by Fan4eGGG** [comment]
> > nah. so i'm not wrong. i don't have any Applications. i use Opera, maybe that's why.
> 
> Opera doesn't support PWA.

Chrome is uncomfortable for me. but I specifically downloaded it to check what it is and it too doesn't have any PWAs or whatever it's called.

**Comment by Fan4eGGG** [comment]
how much more convenient it would have been to just make a PC app.
download, run, connect. thats it.

**Comment by Lisra-git** [comment]
> how much more convenient it would have been to just make a PC app. download, run, connect. thats it.

That's the total opposite of the new experience

**Comment by Fan4eGGG** [comment]
> That's the total opposite of the new experience

"new experience" is about not being able to connect through the PWA?

**Comment by tunaflsh** [comment]
@Fan4eGGG https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DDesktop

**Comment by Fan4eGGG** [comment]
> @Fan4eGGG https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DDesktop

thanks. strange, but Low latancy doesnt work for some reason, there is no change.
and it resets every time I open the app.
