### ISSUE TITLE
and we get NOTHING

### ISSUE THREAD

**Issue by psych0kines** [radiance-project/ear-pc#32]
Imagine that there are companies in the world where developers respect consumers and dont force them to outsource "**official apps**" and release them on github so that genius engineers can take forever to write 2 lines of code for new devices.
_Nothing_ not about that.

**Comment by Lisra-git** [comment]
> Imagine that there are companies in the world where developers respect consumers and dont force them to outsource "**official apps**" and release them on github so that genius engineers can take forever to write 2 lines of code for new devices. _Nothing_ not about that.

Hey
Nothing was very supportive in the whole process, main reason for the delay is that I'm still studying and that I have other priorities 
That said, release is near (1-2w at best)
