### ISSUE TITLE
CMF Buds aren't supported?

### ISSUE THREAD

**Issue by HWdriver** [radiance-project/ear-pc#33]
Neither is windows Bluetooth seeing them, i turned on dual device connection and pressed the pairing button

**Comment by mrbrickstar** [comment]
Hello :)
Ear (PC) has been replaced by Ear (Web), an advanced and improved version of Ear PC that runs locally on your browser. It also supports more nothing audio devices than ear (PC), so I suggest you give that a go first. 

Repo: https://github.com/radiance-project/ear-web
Link: https://earweb.bttl.xyz/

This repo Is now unmaintained and I suggest you reopen your issue on the new repo if the issue still persists. 

If you have any more questions, don't feel afraid to ask :)
Bendix

**Comment by HWdriver** [comment]
> Hello :)
> Ear (PC) has been replaced by Ear (Web), an advanced and improved version of Ear PC that runs locally on your browser. It also supports more nothing audio devices than ear (PC), so I suggest you give that a go first. 
> 
> Repo: https://github.com/radiance-project/ear-web
> Link: https://earweb.bttl.xyz/
> 
> This repo Is now unmaintained and I suggest you reopen your issue on the new repo if the issue still persists. 
> 
> If you have any more questions, don't feel afraid to ask :)
> Bendix

Any reason to switch to a web client?
