### ISSUE TITLE
CMF Buds 2 Pro

### ISSUE THREAD

**Issue by Red1N-Q** [radiance-project/ear-pc#34]
![image](https://github.com/user-attachments/assets/fc5bc957-7b16-41f0-9f0b-50cbf2f10685)
Windows 10 pc with bluetooth recognize my Nothing CMF Buds 2 Pro and even the wheel works to adjust volume but when trying to connect them with app, they aren't visible and i get eroor in attached image.

**Comment by mrbrickstar** [comment]
Hello :)
Ear (PC) has been replaced by Ear (Web), an advanced and improved version of Ear PC that runs locally on your browser. It also supports more nothing audio devices than ear (PC), so I suggest you give that a go first. 

Repo: https://github.com/radiance-project/ear-web
Link: https://earweb.bttl.xyz/

This repo Is now unmaintained and I suggest you reopen your issue on the new repo if the issue still persists. 

If you have any more questions, don't feel afraid to ask :)
Bendix
