### ISSUE TITLE
Grammatical mistake

### ISSUE THREAD

**Issue by royalgillz** [radiance-project/ear-pc#4]
![image](https://github.com/radiance-project/ear-pc/assets/92250502/64414c31-83ce-469b-b914-0366ad1bef41)
![image](https://github.com/radiance-project/ear-pc/assets/92250502/bb6970b2-3869-454f-91ed-f015f36e8782)

There should be **2x Tap** instead of 2x tab as shown in the above pictures

**Comment by mrbrickstar** [comment]
Oh yep thank you, will be fixed in the next build
