### ISSUE TITLE
Only frontend is public

### ISSUE THREAD

**Issue by rewhex** [radiance-project/ear-pc#5]
> For the security of users, the entire backend is kept private for the moment, a mishandling of these tools could affect the proper functioning of the devices, Nothing(R), or Lisra-git or any other contributor to the project cannot be held responsible in case of mishandling related to a modified use of the project outside of its intended use and safety measures in place.

As i see you writing this about the main.pyc file, but for now there is the tools, that allows  anyone to decompile such file to almost the source code. So maybe you don't need to compile it either?

**Comment by Lisra-git** [comment]
Providing a compiled solution allows us to release a "certified" version for debugging/development of the frontend, the main concern being to prevent users from browsing the code too easily and causing problems that would eventually fall on us.

The code will eventually be released at some point, but not for now.
