### ISSUE TITLE
Launcher.exe detected as malicious file.

### ISSUE THREAD

**Issue by itsmeshibintmz** [radiance-project/ear-pc#6]
![image](https://github.com/radiance-project/ear-pc/assets/52344717/4ba0176c-59e4-4529-b63d-560120c07040)

2 security vendors and no sandboxes flagged this file as malicious.

I'm concerned. Is it going to cause any issues?

**Comment by mrbrickstar** [comment]
Hey :D
This is a common occurrence on files that have not been approved by some antivirus (we call these "false positive"). It might detect the launcher as malicious as it's downloading files from GitHub, however I can assure you that these files are required to run ear (PC) and do no harm to your computer or your data. Also, the launcher is Open Source, so If you want to take a look at it, you can find the source code here: https://github.com/radiance-project/ear-pc/blob/main/launcher/launch.py

Also, if you want to learn more about false positives, give this article a read: https://encyclopedia.kaspersky.com/glossary/false-positive/

If you have any more questions, please don't hesitate to continue on this thread :)

**Comment by itsmeshibintmz** [comment]
nothing more. just wanted to confirm. thank you for the quick response.
