### ISSUE TITLE
A javascript error occured in the main process

### ISSUE THREAD

**Issue by itsmeshibintmz** [radiance-project/ear-pc#7]
I have installed with launcher.exe.
When started the app, it asks for scan, then after sometimes it shows this error.
![image](https://github.com/radiance-project/ear-pc/assets/52344717/c9bb729e-670f-49c9-9dab-d24fdc856a18)

**Comment by mrbrickstar** [comment]
Thank you for pointing that out, we will look into this asap. Did you had your buds connected when this happened? Also did restarting the app help?

**Comment by itsmeshibintmz** [comment]
> Thank you for pointing that out, we will look into this asap. Did you had your buds connected when this happened? Also did restarting the app help?

Nope. Not connected.showed while scanning.

**Comment by mrbrickstar** [comment]
Could you try to connect your buds via Bluetooth first and press scan again after you connected?

**Comment by itsmeshibintmz** [comment]
yes let me try.

**Comment by itsmeshibintmz** [comment]
![image](https://github.com/radiance-project/ear-pc/assets/52344717/6b1f2632-a6dc-40dc-94e9-137f4e540668)

it worked. 

for anyone having/may have the same issue, the steps:
1: connect your earbuds normally via bluetooth to your system
2: open ear app, scan, it will display option to select your device and it'll work.
![image](https://github.com/radiance-project/ear-pc/assets/52344717/b39e091b-2cce-49d2-b9a1-03bc7004f435)
